name: Build and test
on:
  push:

permissions:
  checks: write
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          arguments: assemble
      - name: Test with Gradle
        uses: gradle/actions/setup-gradle@v3.4.2
        with:
          arguments: check --continue
      - name: Save ktlint reports
        uses: yutailang0119/action-ktlint@v4
        if: always() # always run even if the previous step fails
        with:
          report-path: '**/ktlint*.xml'
      - name: Save detekt reports
        uses: github/codeql-action/upload-sarif@v3
        if: always() # always run even if the previous step fails
        with:
          sarif_file: build/reports/detekt
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
