name: Build and test
on:
  push:

permissions:
  checks: write
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Test with Gradle
        run: ./gradlew check --continue
      - name: Save ktlint reports
        uses: yutailang0119/action-ktlint@v5
        if: always() # always run even if the previous step fails
        with:
          report-path: '**/ktlint*.xml'
      - name: Save detekt cli report
        uses: github/codeql-action/upload-sarif@v3
        if: always() # always run even if the previous step fails
        with:
          sarif_file: build/reports/detekt/.cli.sarif
          category: "detekt-cli"
      - name: Save detekt compiler report
        uses: github/codeql-action/upload-sarif@v3
        if: always() # always run even if the previous step fails
        with:
          sarif_file: build/reports/detekt/.compiler.sarif
          category: "detekt-compiler"
      - name: Save detekt processor report
        uses: github/codeql-action/upload-sarif@v3
        if: always() # always run even if the previous step fails
        with:
          sarif_file: build/reports/detekt/.processor.sarif
          category: "detekt-processor"
      - name: Save detekt processor-api report
        uses: github/codeql-action/upload-sarif@v3
        if: always() # always run even if the previous step fails
        with:
          sarif_file: build/reports/detekt/.processor-api.sarif
          category: "detekt-processor-apiy"
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
